services:
  frontend:
    build:
      context: ./Frontend
    container_name: frontend_makeway
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend_makeway
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/makeway
    volumes:
      - ./Backend:/app
    restart: always

  db:
    image: postgres:15
    container_name: db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: makeway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
