const ITEMS_PER_PAGE = 5;

const LOCAL_LUNCH_THRESHOLD = 14 * 60;
const LOCAL_DINNER_THRESHOLD = 21 * 60;

const INTERNATIONAL_LUNCH_THRESHOLD = 10 * 60 + 30;
const INTERNATIONAL_DINNER_THRESHOLD = 17 * 60 + 30;

export {
  ITEMS_PER_PAGE,
  LOCAL_LUNCH_THRESHOLD,
  LOCAL_DINNER_THRESHOLD,
  INTERNATIONAL_LUNCH_THRESHOLD,
  INTERNATIONAL_DINNER_THRESHOLD,
};
