// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc8O-FiyU73SPGd7msQQBPM0XoO6vwhjY',
    appId: '1:89050510585:web:08e04edeb93c3abaad9e28',
    messagingSenderId: '89050510585',
    projectId: 'tapa-buracos',
    authDomain: 'tapa-buracos.firebaseapp.com',
    storageBucket: 'tapa-buracos.appspot.com',
    measurementId: 'G-XCS9CVP0W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCXyNSn-ib98qGyDXHnbyBkxRoMya2egI',
    appId: '1:89050510585:android:5669b1ed6b4a118dad9e28',
    messagingSenderId: '89050510585',
    projectId: 'tapa-buracos',
    storageBucket: 'tapa-buracos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7alCIM1ZllocrlxgAD95kffESLLwiw8U',
    appId: '1:89050510585:ios:81c28b2f07b4ce33ad9e28',
    messagingSenderId: '89050510585',
    projectId: 'tapa-buracos',
    storageBucket: 'tapa-buracos.appspot.com',
    iosBundleId: 'com.tapaburacos.tapaBuracos',
  );
}
